version: '3.8'
services:
  db:
    image: mysql
    container_name: DeliverApp_db
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/seed_script.sql
